name: boost

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Version tag name'
        required: true
        default: '8.0.0'
      pwd_val:
        description: 'Docker PWD'
        required: true
        default: ''

jobs:
  build:
    name: Build Images
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Push Image
        run: chmod +x push_aliyun.sh && bash push_aliyun.sh ${{ github.event.inputs.tag_name }} ${{ github.event.inputs.pwd_val }}
